apiVersion: tekton.dev/v1beta1
kind: PipelineResource
metadata:
  name: quarkuscoffeeshop-customermocker-image
  labels:
    app: quarkuscoffeeshop-customermocker
  namespace: quarkuscoffeeshop-cicd
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-customermocker
