---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: quarkuscoffeeshop-cicd
  generateName: quarkuscoffeeshop-barista-
  labels:
    app: quarkuscoffeeshop-barista
    argocd.argoproj.io/instance: quarkuscoffeeshop-cicd
    tekton.dev/pipeline: build-and-push-quarkuscoffeeshop-barista
spec:
  pipelineRef:
    name: build-and-push-quarkuscoffeeshop-barista
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: quarkuscoffeeshop-barista-shared-workspace-pvc
    - name: maven-settings
      persistentVolumeClaim:
        claimName: quarkuscoffeeshop-barista-maven-settings-pvc
